export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';
export const SET_PRODUCT_IMAGES = 'SET_PRODUCT_IMAGES';
export const SET_PRODUCT_DESCRIPTION = 'SET_PRODUCT_DESCRIPTION';
export const SET_PRODUCT_REVIEW = 'SET_PRODUCT_REVIEW';
export const SET_PRODUCT_OFFERS = 'SET_PRODUCT_OFFERS';
export const SET_PRODUCT_PROMOTIONS = 'SET_PRODUCT_PROMOTIONS';
export const SET_PRODUCT_RETURNPOLICY = 'SET_PRODUCT_RETURNPOLICY';
export const PRODUCT_API_ERROR = 'PRODUCT_API_ERROR';